#!/bin/sh
set -e

# Write avian.conf from environment variables so secrets are not baked into the image.
AVIAN_DIR="/avian/.avian"
mkdir -p "$AVIAN_DIR"

# The Docker volume is created as root — fix ownership before dropping privileges.
chown -R avian:avian "$AVIAN_DIR"

cat > "$AVIAN_DIR/avian.conf" << EOF
# Generated by Docker entrypoint — do not edit manually

server=1
daemon=0

# Indexes required by the Avian API
txindex=1
assetindex=1
timestampindex=1
spentindex=1
addressindex=1
coinstatsindex=1

# RPC
rpcuser=${AVIAN_RPC_USER:?AVIAN_RPC_USER is required}
rpcpassword=${AVIAN_RPC_PASS:?AVIAN_RPC_PASS is required}
rpcallowip=0.0.0.0/0
rpcbind=0.0.0.0
rpcport=7896

# P2P
port=8814

# Performance
dbcache=512
maxmempool=300
EOF

# Run as the avian user (gosu drops root safely)
exec gosu avian aviand -datadir="$AVIAN_DIR" -conf="$AVIAN_DIR/avian.conf" "$@"
